[mypy]
python_version = 3.14

# relative path to the source code of the eddsa-threshold package and the pyscript-stubs package
mypy_path = ../eddsa-threshold/src:~/pyscript-stubs/src/pyscript-stubs

pretty = True
show_error_codes = True